<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>New Webpage</title>
        <link rel='stylesheet' href='style.css'/>
        <script src='script.js'></script>
    </head>
    <body>
      <img src='https://www.khanacademy.org/computer-programming/thediamondmincart-in-a-diamond-minecart/6068289164935168/5723151296102400.png' class='Khan1'>
      <img src='https://www.khanacademy.org/computer-programming/teeny-clicker-112-hacked/6102461870899200/5629499534213120.png' class='Khan2'>
      <button id='Khan1'>Contest 1</button>
      <button id='Khan2'>Contest 2</button>
    </body>
</html>
